### ISSUE TITLE
napalm-base needs to be refactored

### ISSUE THREAD

**Issue by v1k0d3n** [charter-ctec/dockerfiles#6]
@EckyYakov: we need to refactor the napalm-base container to be more flexible. make sure to use args for the versions, etc like we've talked about in the past with other images.

**Comment by EckyYakov** [comment]
Yep, working on making it more flexible and testing out its practicality currently. I'll let you know how it's going

**Comment by v1k0d3n** [comment]
awesome job with cleaning up the commit. i'll show you how you can tie the issue to your commit next time, so the commit closes out the issue automatically. closing this for now.
